### ISSUE TITLE
paradox-upgrade-packages not working with Emacs 25

### ISSUE THREAD

**Issue by benswift** [Malabarba/paradox#122]
Hi folks

On OSX 10.11 and Emacs 25.1.1 (emacs-mac-port), `M-x paradox-upgrade-packages` gives me
```
Overriding package-menu--print-info with paradox--print-info
Overriding package-menu--print-info-simple with paradox--print-info
Overriding package-menu--generate with paradox--generate-menu
Overriding package-menu-mode with paradox-menu-mode
Importing package-keyring.gpg...done
Contacting host: raw.githubusercontent.com:443
Opening TLS connection to ‘raw.githubusercontent.com’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 raw.githubusercontent.com’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 raw.githubusercontent.com --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect raw.githubusercontent.com:443 -no_ssl2 -ign_eof’...done
Opening TLS connection to ‘raw.githubusercontent.com’...done
Waiting for refresh to finish...
No operations specified.
```
If I just to a `list-packages`, mark for upgrades and then execute, it works fine.

Is it an Emacs 25 issue? I know the packaging stuff has changed.

**Comment by Malabarba** [comment]
Thanks for the report, but could you provide a little more info? What
happens when you call the command? Do you get an error message?

**Comment by benswift** [comment]
Hi there,

When I (interactively) call `paradox-upgrade-packages` it dumps those lines to the `*Messages*` buffer, and the final thing I see in the minibuffer is "No operations specified".

However, if after that, I do a regular `list-packages`, then mark upgrades with `U` and execute with `x`, it says "x packges marked for upgrading" and goes and upgrades them all.

**Comment by benswift** [comment]
Later on this arvo I'll have a bit more time, I can step through it and figure out why it's thinking there's nothing to upgrade. I was just wondering if "not working on Emacs 25" was a known issue.

**Comment by Malabarba** [comment]
Ah sorry. I hadn't seen the lines you posted above because the email notification I got did not include them. I guess this probably broke because I forgot to disable asynchronous refreshing while `package-upgrade-packages` is doing its thing.

**Comment by benswift** [comment]
Ok, no worries. Let me know if there's anything else you want me to
investigate/test.

Thanks mate.

**Comment by Malabarba** [comment]
> I guess this probably broke because I forgot to disable asynchronous refreshing while package-upgrade-packages is doing its thing.

Nope, I just checked it and the code looks correct. I also can't reproduce the problem (the command works fine for me on Emacs 25). =/

**Comment by benswift** [comment]
I noticed that I had `(setq paradox-execute-asynchronously t)` in my init file, and when I deleted that everything worked fine. I can't easily check that that was the problem for sure, because I need to wait for MELPA to update to give `paradox-upgrade-packages` something to do. Anyway, thanks for your help, and you can close this.

**Comment by malcolmpurvis** [comment]
For the record I had a similar problem when I moved from Emacs 24.5 to latest version of 25.2 from the git repo.  In my case `paradox-list-packages `would list the current packages but would never list new packages.  I do not have `paradox-execute-asynchronously` set.

My solution was to delete the paradox package from my ~/.emacs.d and reload it from MELPA.

My guess is that there is some macro that has changed so that code compiled with Emacs 24 will not work in Emacs 25.

**Comment by mfiano** [comment]
I just updated to Emacs 25.1, and I was getting a similar issue with paradox-list-packages hanging at connecting to raw.githubusercontent.com:443. Possibly due to the feature:

```
Enhanced network security (TLS/SSL certificate validity and the like) via the new Network Security Manager (NSM).
```

The paradox window would have the loading animation on the bottom, but otherwise usable. Deleting elpa and recompiling everything fixed the problem.

**Comment by thjwong** [comment]
Similar to mfiano, I just updated to Emacs 25.1 (Windows) and encountered the exact same problem.
Removing paradox from ELPA and then using package-list-packages to reinstall paradox did not solve the problem, i.e. the paradox window would have the loading animation "(Paradox Menu: loading...)" at the bottom, but otherwise usable.
Adding the following line to the init file will terminate the connecting action after 5-10+ seconds.
(prefer-coding-system 'utf-8)

**Comment by rsuhada** [comment]
Same problem here, unfortunately... After upgrade to 25.1 (linux) I too deleted my ELPA dir and freshly reinstalled everything, but paradox-upgrade-packages still gives "No operations specified."

**Comment by Malabarba** [comment]
Are you still having this issue? I'm on latest emacs and the command work for me.
