### ISSUE TITLE
Show where a package was installed from

### ISSUE THREAD

**Issue by rdiez** [Malabarba/paradox#172]
I believe that the GNU ELPA repository has dropped package etags-select . This is probably because find-tag / etags.el is being deprecated. I am still investigating this issue on my computers.

During that investigation, I have realised that Paradox does not show where a package has been installed from. For example:

---8<---8<---8<---
bm is an installed package.

     Status: Installed in ‘bm-20181012.1631/’ (unsigned). Delete
    Version: 20181012.1631
    Summary: Visible bookmarks in buffer.
   Homepage: https://github.com/joodland/bm
   Keywords: bookmark highlight faces persistent 
Other versions: 20181012.1631 (melpa).

[back]
---8<---8<---8<---

Note that, for this package, there is an "Other versions" line, so Paradox knows that the package is in GNU ELPA and in MELPA. But it does not say that the version installed came from GNU ELPA.

The real bonus for me would be to say that a currently-installed package has come from a particular repository, but is no longer available in that repository, or maybe in no other repository. That means trouble. At the very least, the package will no longer be upgraded. And, if you install Emacs on a fresh PC, the package will no longer be available. That is what just happened to me with etags-select. It would have been better to get an early warning, than fixing the breakage afterwards, when maybe you are under time pressure.

**Comment by Malabarba** [comment]
Hey there.
Paradox doesn't know where the package was installed from. 

That page you see (which, btw, is from package.el, not Paradox :-)) only displays the melpa version in "other versions" because it identifies that melpa is the only repository with a different version number for this package. For instance, if you have this package on GNU Elpa and on Melpa Stable with the same version, they will both be omitted from that buffer, because package.el doesn't actually know where it was installed form.
