### ISSUE TITLE
Use 'font-lock-face for propertizing instead of 'face

### ISSUE THREAD

**Issue by tsdh** [Malabarba/paradox#73]
paradox looses fontification if something calls `font-lock-ensure` is its buffer (see, e.g., this [swiper issue](https://github.com/abo-abo/swiper/issues/44)).  That's because it propertizes using `'face` whereas it should use `'font-lock-face`.  Additionally, if it only propertizes explicitly and there are no font-lock keywords, then it could set `font-lock-defaults` to `(nil t)`.

See `(info "(elisp)Font Lock Basics")`, especially the last paragraph.

**Comment by Malabarba** [comment]
I'll look into that info page. Do you have a link to it on the Web? (I'm away from home and typing on a phone) 

I understand the difference between face and font-lock-face, but I'm not convinced that a package should generally use the latter instead of the former. I'll try to read that swiper issue as well.

**Comment by tsdh** [comment]
Yes, I do.  https://www.gnu.org/software/emacs/manual/html_node/elisp/Font-Lock-Basics.html#Font-Lock-Basics

My basic understanding is that if you propertize explicitly and you don't want font-lock to override/erase your explicit fontification, then you should use `font-lock-face`.

**Comment by Malabarba** [comment]
> Yes, I do.  https://www.gnu.org/software/emacs/manual/html_node/elisp/Font-Lock-Basics.html#Font-Lock-Basics

Thanks 

> My basic understanding is that if you propertize explicitly and you don't want font-lock to override/erase your explicit fontification, then you should use `font-lock-face`.

Precisely. Which is why it shouldn't be an issue for major modes that don't use font locking. I guess this may be fixed if paradox locally sets to nil those font lock variables you mentioned (though I don't see why they're not nil in the first place). If that doesn't fix it, I'd be inclined to call it a swiper issue (though I haven't read that other thread yet).

**Comment by Malabarba** [comment]
Actually, I just noticed paradox uses a mix of face and font-lock-face, which is something it inherited from package.el and is definitely wrong. So in the very least I'll have to normalise that.
