### ISSUE TITLE
Header line is off after opting out of Github integration

### ISSUE THREAD

**Issue by wasamasa** [Malabarba/paradox#84]
I didn't feel like setting this feature up, so I've opened the package menu and got this:

![](http://i.imgur.com/XGHjIZT.png)

I'd assume that if there's no column for Github stars in the lines, the header line shouldn't have a column either...

**Comment by Malabarba** [comment]
That's odd. Github integration allows you star/unstar packages, but it should not affect the star listing.

It looks like the contents of your Package buffer are being populated by package.el instead of Paradox. There are other things missing, like the homepage links and the different colors for the columns.

Maybe this is related to #86 ? (Or maybe you realised that already and I'm just a couple of days late to the party)

**Comment by Malabarba** [comment]
You're on Emacs `master` right?
I just found a bug related to a new feature in `tabulated-list-print` which would explain your issue if you had already run `list-packages` once before calling `paradox-list-packages`.

**Comment by wasamasa** [comment]
I'm on Emacs 24.5 and FWIW, can no longer reproduce it either.

**Comment by wasamasa** [comment]
Or wait, I actually do. I've done `M-x list-packages`, then `M-x package-list-packages` and hit `C-g` as it locked up Emacs. That gave me a half-loaded view as in the screenshot.

**Comment by Malabarba** [comment]
Ok, then paradox probably never got a chance to print its own stuff, which is why you still see the old buffer. So this will be fixed when we fix your hang.

**Comment by wasamasa** [comment]
Closing as #86 got closed.
