### ISSUE TITLE
Noticable delay when calling paradox-list-packages. 

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/paradox#87]
## Setup:
GNU Emacs GUI version 24.4.51.1 (x86_64-w64-mingw32) 
[Compiled from Harroogan Emacs.](https://bitbucket.org/Haroogan/emacs-for-windows/)
Paradox-mode, using the latest version of web-mode from GitHub
Windows 7 x64 bit.

## Situation:
When calling `pacakge-list-packages`, the delay is somewhat 4 seconds. In the minibuffer you will notice he is connecting to the package hosts like MELPA and GNU or ORG hosts. 
When calling `paradox-list-packages`, the delay is huge when Emacs started for the first time. It's around 20 seconds. 

Especially when concurrency is now possible in Elisp (which is all done of your work, Malabarba!), I'm beginning to wonder what causes such a delay,

**Comment by Malabarba** [comment]
Paradox does 2 requests more than the regular package menu, one to its own database of star-counts and download-counts, and another to get the user's list of starred packages (only if you have github integration configured).
A bigger delay is inevitable without concurrent downloads, but the increase you report is definitely unusual. It usually doesn't take that long, do you happen to be on a slow connection?

> Especially when concurrency is now possible in Elisp (which is all done of your work, Malabarba!), I'm beginning to wonder what causes such a delay

Concurrency would certainly help a lot here, but you'll need to use the Emacs master branch to get that.

**Comment by autosquid** [comment]
is there any time schedule for concurrency in paradox?

**Comment by Malabarba** [comment]
@autosquid
Just to be clear, concurrent package installation is already part of Paradox. 
Meanwhile, concurrent refreshing of the package list not *technically* part of Paradox.

However, concurrent refreshing of the package list *is* implemented on the Emacs core for the (yet unreleased) 25.1 Emacs version. 
So if you use Emacs 25.1, you **will have concurrent refreshing in Paradox**.

Outside of that, I don't plan to implement concurrent refreshing directly in Paradox. Simply because anyone who wants concurrent refreshing simply needs to upgrade to Emacs 25.

**Comment by ReneFroger** [comment]
Can confirm this. Just upadted to Emacs 25.0.50.1, downloaded from [here](http://sourceforge.net/projects/emacsbinw64/compiled). 
Seems this have concurrent refreshing in the `package-list-packages`, and now Paradox responds fast again. 

Thanks for your helpful response, by the way!
